In [1]:
import torch

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [5]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
torch.randn(3,4)

tensor([[-0.7230,  0.2696,  1.0006, -1.8672],
        [ 0.7147,  0.8352,  0.0717,  0.2634],
        [ 1.3166, -0.6782, -0.0946, -0.4804]])

In [9]:
x = torch.tensor([1,2,3,4])
y = torch.tensor([3,4,5,6])
x + y, x-y, x*y ,x**y

(tensor([ 4,  6,  8, 10]),
 tensor([-2, -2, -2, -2]),
 tensor([ 3,  8, 15, 24]),
 tensor([   1,   16,  243, 4096]))

In [10]:
torch.exp(x)

tensor([ 2.7183,  7.3891, 20.0855, 54.5981])

In [11]:
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.ones(3,4)
x , y 

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [12]:
torch.cat((x,y),dim=0), torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.],
         [ 1.,  1.,  1.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  1.,  1.,  1.],
         [ 4.,  5.,  6.,  7.,  1.,  1.,  1.,  1.],
         [ 8.,  9., 10., 11.,  1.,  1.,  1.,  1.]]))

In [13]:
x == y

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [22]:
x < y

tensor([[ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [15]:
y.sum()

tensor(12.)

In [16]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [17]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [18]:
x[1],x[0:3]

(tensor([4., 5., 6., 7.]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [19]:
x[2,3] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10.,  9.]])

In [21]:
x[0,:] = 0
x

tensor([[ 0.,  0.,  0.,  0.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10.,  9.]])

In [25]:
a = torch.arange(6).reshape((2,3,1))
b = torch.arange(2).reshape((1,1,2))
a,b

(tensor([[[0],
          [1],
          [2]],
 
         [[3],
          [4],
          [5]]]),
 tensor([[[0, 1]]]))

In [26]:
a + b

tensor([[[0, 1],
         [1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5],
         [5, 6]]])