In [14]:
import torch
x = torch.tensor(3.0)
y = torch.tensor(4.0)
x+y,x*y,x-y,x**y

(tensor(7.), tensor(12.), tensor(-1.), tensor(81.))

In [15]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
len(x)

12

In [17]:
x.shape

torch.Size([12])

In [18]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [19]:
x.T

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [20]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
B = A.clone()
A,B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))

In [21]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [25]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0

tensor([40., 45., 50., 55.])

In [26]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1

tensor([ 6., 22., 38., 54., 70.])

In [27]:
A.sum()

tensor(190.)

In [28]:
A.mean()

tensor(9.5000)

In [29]:
A_sum_axis0 / A.shape[0]

tensor([ 8.,  9., 10., 11.])

In [30]:
sum_A = A.sum(axis=1,keepdims = True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [31]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [32]:
x = torch.arange(4,dtype = torch.float32)
y = torch.ones(4,dtype =torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [33]:
torch.sum(x*y)

tensor(6.)

In [35]:
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [36]:
B = torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [37]:
a = torch.tensor([3.0,4.0])
torch.norm(a)

tensor(5.)

In [38]:
torch.abs(a).sum()

tensor(7.)

In [39]:
torch.norm(torch.ones((4,9)))

tensor(6.)

In [40]:
A = torch.arange(12).reshape(3,4)
B = torch.ones(12).reshape(3,4)
A,B,A.T.T,A.T+B.T,(A+B).T

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 1.,  5.,  9.],
         [ 2.,  6., 10.],
         [ 3.,  7., 11.],
         [ 4.,  8., 12.]]),
 tensor([[ 1.,  5.,  9.],
         [ 2.,  6., 10.],
         [ 3.,  7., 11.],
         [ 4.,  8., 12.]]))

In [42]:
a = torch.ones(24).reshape(2,3,4)
a,len(a)

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 2)

In [46]:
A,A/A.sum(axis=0)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[0.0000, 0.0667, 0.1111, 0.1429],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.6667, 0.6000, 0.5556, 0.5238]]))

In [48]:
A,A.sum(axis=0),A.sum(axis=1)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([12, 15, 18, 21]),
 tensor([ 6, 22, 38]))

In [49]:
a.sum(axis=0).shape,a.sum(axis=1).shape,a.sum(axis=2).shape

(torch.Size([3, 4]), torch.Size([2, 4]), torch.Size([2, 3]))